name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: {python-version: "3.10"}
    - uses: abatilo/actions-poetry@v3
    - run: poetry install --with dev
    - run: poetry run ruff check .
    - run: poetry run pytest -q
